### ISSUE TITLE
You're running an unknown version of Mylar. Update or Close

### ISSUE THREAD

**Issue by dwightstanley** [linuxserver/docker-mylar#28]
Running Unraid 6.6.6 - Mylar docker says it is up-to-date.
Image Version Number: Linuxserver.io version:- 101e6aa7-ls7 Build-date:- 2019-02-05T18:47:01+00:00
Bottom center of Mylar Homepage has written: Version: None (master) 
In the Mylar Docker a popup in the lower right states: You're running an unknown version of Mylar. Update or Close

**Comment by thelamer** [comment]
We know, trust us we know. 
Given it looks like this issue will keep getting filed I am gonna PR to just checkout at the specific commit instead of downloading the version at a commit. 

At the core of this is the applications dependance on the git tree being present for determining it's own versioning . We actually do not want people updating inside the container as it is on a path that exists inside the container  and causes issues for people that may later use docker to update. 
Optimally the developer of this application would use an alternative tagging method for releases. 

But in the mean time we also do not want to field repeated support requests regarding this popup .

**Comment by thelamer** [comment]
@dwightstanley closing this as will be resolved when this gets merged https://github.com/linuxserver/docker-mylar/pull/29
